### ISSUE TITLE
ZoF fails to build on FreeBSD 13.0-CURRENT (since r349846)

### ISSUE THREAD

**Issue by fbynite** [zfsonfreebsd/ZoF#115]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	|  FreeBSD 13.0-CURRENT r349857
Distribution Version	| 
Linux Kernel	| 
Architecture	|  amd64
ZFS Version	|  ZoF (commit: e398e9423)
SPL Version	| 

### Describe the problem you're observing

ZoF won't build on FreeBSD-CURRENT, it complains with:

```implicit declaration of function vm_page_hold```

Since FreeBSD-CURRENT (r349846), the vm_page hold and wire mechanisms have been merged. See [https://reviews.freebsd.org/D19247](D19427) for details - specifically the changes to zfs_vnops.c.

The changes from r349846 to zfs_vnops.c will need to be brought in at some point. 

I've applied those changes to my local copy and I'm now able to compile the kernel module.

**Comment by ghost** [comment]
Should be fixed by ff8aed797, if not please reopen.
